### ISSUE TITLE
Update Installation Dependencies

### ISSUE THREAD

**Issue by johnfosborneiii** [chainguard-dev/melange#118]
Even though the README install instructions run inside of a container, they run as privileged and leverage workstation dependencies. On Fedora I had to install:
dnf install qemu-user-static for instance to get my build working. Need to do some testing in other environments to see what the requirements are. However, could we just make a note in the README for now?

**Comment by ltagliaferri** [comment]
@johnfosborneiii, we added this to the [Troubleshooting melange page](https://edu.chainguard.dev/open-source/melange/troubleshooting/#missing-qemu-user-space-emulation-packages), does this satisfy this issue for you?
