### ISSUE TITLE
bubblewrap (bwrap) builds with non-zero uid while docker runner runs with uid 0.

### ISSUE THREAD

**Issue by smoser** [chainguard-dev/melange#1255]
The bubblewrap runner builds with uid of the user, but the docker runner builds with uid=0.

That causes a problem for anything that behaves differently in those cases.  It can be illustrated with [wolfi-dev/os/datadog-agent.yaml at f635663eae72d624c](https://github.com/wolfi-dev/os/blob/f635663eae72d624c04877b487dea451572568f7/datadog-agent.yaml) .

This package
 *  with bwrap tries to use sudo to become root and fails to build (sudo is not present)
 *  with docker runner works , other than in my environment it will not build at all due to #1254

**Comment by krishjainx** [comment]
The merged PR introduces parity between Bubblewrap and Docker. This can be closed :)
