### ISSUE TITLE
`no-provides` disables SCA depends (aka no-depends)

### ISSUE THREAD

**Issue by xnox** [chainguard-dev/melange#1366]
I believe this is regression introduced in 2c11e1bfe62b7a5489b526911a9dfea72d740168

Exposed in https://github.com/wolfi-dev/os/pull/23719 by gcc-12 which has `options: no-provides: true` with intention not to provide duplicate / conflicting commands (however, no longer needed as all binaries are uniquely named with suffixes).

However the above commit appears to nuke SCA Depends as well as Provides behind the `no-provides` option. 

In https://github.com/chainguard-dev/melange/blob/ad395d68d0c8e57ba2c1f4b261f7325ed2239b68/pkg/sca/sca.go#L679 I expect only provides-only generators to be gated behind "no-provides" (as in cmd:providers and pc: provides), and ensure that Deps generators are gated behind "no-depends".

Timing matches because gcc-12 was last built in December 2023, and rebuilt only just recently, hence the January 2024 change in melange has potentially been missbuilding a few packages, or some packages started to rely on the fact that "no-provides" has been implying "no-depends" since January.

cc: @smoser @pnasrat @imjasonh @jonjohnsonjr

**Comment by imjasonh** [comment]
That sounds right based on the diff. We can fix this today, I don't remember why I exited early on no provides alone.

**Comment by xnox** [comment]
> That sounds right based on the diff. We can fix this today, I don't remember why I exited early on no provides alone.

no rush, but need to analyse how many packages are affected/regressed/depend on this behaviour.

**Comment by xnox** [comment]
```diff
$ git diff busybox.yaml
diff --git a/busybox.yaml b/busybox.yaml
index 9fc1bf145..2a16aa839 100644
--- a/busybox.yaml
+++ b/busybox.yaml
@@ -1,12 +1,14 @@
 package:
   name: busybox
   version: 1.36.1
-  epoch: 10
+  epoch: 11
   description: "swiss-army knife for embedded systems"
   copyright:
     - license: GPL-2.0-only
   dependencies:
     provider-priority: 10
+  options:
+    no-provides: true
   scriptlets:
     trigger:
       paths:
```

is reproducer, after applying this - `make package/busybox test/busybox` fails with missing runtime libraries.
