### ISSUE TITLE
git-checkout arbitrary SHA

### ISSUE THREAD

**Issue by arodland** [chainguard-dev/melange#1411]
I'm very interested in using melange, but some of the things I need to package have upstream in git and no versioning at all. No releases, no tags, and no branches I would care to track the HEAD of.

I'm perfectly okay with managing these by hand, with `version: 0.0_git20240801` and pinning to a specific commit SHA, but `git-checkout` can only specify a branch or a tag, not a commit. Using a `runs` block is possible, but annoying if you want to recreate all of the other stuff the git-checkout pipeline does.

Can we support this workflow?

**Comment by xnox** [comment]
I believe this is resolved no?

One cannot really clone a specific hash, only at least a remote head.

if one sets depth -1 and expected commit, latest melange will reset to said commit assuming it is somewhere in the history of current remote head.

**Comment by arodland** [comment]
For anyone searching, the PR that enables this was #1516 .
