### ISSUE TITLE
include melange version information in apk .PKGINFO

### ISSUE THREAD

**Issue by smoser** [chainguard-dev/melange#1534]
https://github.com/wolfi-dev/os/issues/29688#issue-2555568289 shows an interesting failure path where the pre-commit environment must have differered from the post-commit. (I think).  It gave me the thought that it might be nice to see version information about melange in the .PKGINFO file.

ie, we currently get `Generated by melange`
Maybe we could get `Generated by melange v0.12.1-7-g94476be`
?

**Comment by xnox** [comment]
This was intentionally removed, as it was causing non-reproducible builds across melange updates.
Also post-submit uses wolfictl build, not melange directly and was printing wolfictl version there.
The build logs should indicate melange version used..... and if they don't we should fix that.

See https://github.com/chainguard-dev/melange/commit/0ac1467654a1c9315fe8eac820671ff6b8dc1603

**Comment by smoser** [comment]
good point.
