### ISSUE TITLE
rust seems to be missing an so: dependency

### ISSUE THREAD

**Issue by justinvreeland** [chainguard-dev/melange#1536]
Our rust package doesn't provide `so:librust_driver.....`. Other distros including alpine do.  This hasn't been an issue because nothing was requiring that library.  After  https://github.com/chainguard-dev/melange/pull/1526 the dependency is being added in rust but isn't present as a provides in rust.

```
tar tvf ./packages/x86_64/rust-1.81-1.81.0-r0.apk  | grep librustc_driver
-rw-r--r-- root/docker  78827616 2024-09-28 20:00:07 usr/lib/librustc_driver-28b4e9cad0e1dafd.so


tar -Oxz .PKGINFO < ./packages/x86_64/rust-1.81-1.81.0-r0.apk | grep librustc_driver
depend = so:librustc_driver-28b4e9cad0e1dafd.so
```

Current with no provides or depends but does have the file installing into /usr/lib/.   

https://apk.dag.dev/https/packages.wolfi.dev/os/aarch64/rust-1.81-1.81.0-r0.apk@sha1:37ab7c46fc4e41f9fcecf1993d175ef53956677e/.PKGINFO

**Comment by justinvreeland** [comment]
@xnox  is this what you predicted? As far as I can tell it seems like providing that depending and providing that .so are correct.

**Comment by justinvreeland** [comment]
Hopefully I just missed some corresponding '.so.'

**Comment by xnox** [comment]
Also it has this cute thing: `usr/lib32/*.so` as in that.

**Comment by xnox** [comment]
it also sets rpath

```
0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../lib]
```

**Comment by justinvreeland** [comment]
we can turn rpath off in the configure, I have it off on my current local builds.

**Comment by xnox** [comment]
and the soname is

```
 0x000000000000000e (SONAME)             Library soname: [librustc_driver-28b4e9cad0e1dafd.so]
```

**Comment by xnox** [comment]
so this sounds like legitimate thing. haskell ocaml do similar as well btw. pretty sure the hash here depends on the compiler version and source code content etc. meaning it is stable abi; for matching compiler and toolchain.

given it is shipped within the same packakge; one can argue that one doesn't need to neither depend nor provide it.
As provides are exclusive.

In most other packaging systems, when trying to resolve and find shared library dependencies, normally the `${{targets.destdir}}/usr/lib,${{targets.contextdir}}/usr/lib,....` are all added to the search path. Such that self-referencing libraries are declared in provides; but not in depends.

However, self-serve provides and depends works too. Also not sure if it is a public library; or private to rust.

```
36eddaa8f776:/# apk info --provides systemd | grep so: | sort -u
so:libnss_myhostname.so.2=2
so:libnss_mymachines.so.2=2
so:libnss_resolve.so.2=2
so:libnss_systemd.so.2=2
so:libsystemd-core-253.so=0
so:libsystemd-core-254.so=0
so:libsystemd-core-255.so=0
so:libsystemd-core-256.so=0
so:libsystemd-shared-253.so=0
so:libsystemd-shared-254.so=0
so:libsystemd-shared-255.so=0
so:libsystemd-shared-256.so=0
so:libsystemd.so.0=0
so:libudev.so.1=1

36eddaa8f776:/# apk info --depends systemd | grep so: | sort -u
so:ld-linux-x86-64.so.2
so:libblkid.so.1
so:libc.so.6
so:libcap.so.2
so:libcrypt.so.1
so:libcrypto.so.3
so:libfdisk.so.1
so:libm.so.6
so:libmount.so.1
so:libssl.so.3

36eddaa8f776:/# find . -name libsystemd-core-256.so
./usr/lib/systemd/libsystemd-core-256.so
```

I'm not sure how the above is achieved. In most other packaging systems, this private internal library is neither provided nor depended upon. But we would want provides and depends if/when we split binaries that use that private internal library.

**Comment by xnox** [comment]
@justinvreeland  a file that is not a symlink and starts with `lib.*.so` and is in the public dlopenable location should generate depends and provides.

I don't know what should or should not happen with `/usr/lib/systemd/libsystemd-core-256.so` though. As that's not a default search location.

**Comment by xnox** [comment]
most packaging systems allow one to include/exclude extra search paths. and treat them as public or private (include in dependency graphs or not). It is confusing.

**Comment by justinvreeland** [comment]
Seems like libsystemdcore is being properly detected as vendor'd. I've never had to use that functionality from my package manager and I think I'm glad for that.

**Comment by xnox** [comment]
Attempted rebuild
https://github.com/wolfi-dev/os/pull/30128

elastic build - did not generate neither depends nor provides
github actions - did not generate provides, did generate depends

I am perplexed as to why. Also perplexed as to the difference between the two.

**Comment by xnox** [comment]
Fetching download from https://github.com/wolfi-dev/os/pull/30128/checks?check_run_id=31130590397 and copying in yaml file and using melange scan on it, produces the GHA output. So can debug from here.

**Comment by xnox** [comment]
adding lots of print statements:

```
2024/10/06 06:25:21 INFO scanning usr/lib/librustc_driver-28b4e9cad0e1dafd.so
2024/10/06 06:25:21 INFO usr/lib/librustc_driver-28b4e9cad0e1dafd.so: wrong permissions
```

It is not marked as executable for some reasons.

**Comment by xnox** [comment]
library is not marked as executable, and hence no provides generated.
once marked as executable, provides is generated and depends is excluded (as it's the same package).
