### ISSUE TITLE
Bubblewrap runner does not run as 1000 (build)

### ISSUE THREAD

**Issue by maxgio92** [chainguard-dev/melange#1570]
### Context

The Bubblewrap pipeline is run with same uid of the user that run `melange`, even though in differnt user namespaces. Only that uid is mapped inside the Bubblewrap user namespace, and not 1000 as standard and as already set in passwd via apko.

```
$ id -u
1001
$ melange build --runner=bubblewrap .. &
$ cat /proc/$(pgrep mycommand_in_bubblewrap)/uid_map
      1001       1001          1
```

Considering that my uid on the root user namespace is 1001, when I run `melange build --runner=bubblewrap` the pipeline runs commands as 1001 in a different user namespace but mapping 1001 of that user ns to 1001 of the host user namespace of the process that executed melange.

### Expected behaviour

To have the pipeline be run in a different user namespace, **but** with the id of the user that run `melange` in that process's user namespace, be mapped to a consistent uid in the Bubblewrap user namespace.

Indeed, the passwd entry is also created with name build and uid and gid 1000. 

### How to reproduce

Test pipeline:

```yml
$ cat <<EOF >test.yaml
package:
  name: test
  version: 0.1.0
  epoch: 0

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - runs: |
      echo "running as $(id)"
      echo "build user is $(id build)"
      echo "running sleep..."
      sleep infinity
      exit 1
EOF
```
```shell
$ melange build test.yaml --runner bubblewrap [...]

...
2024/10/18 19:14:58 INFO running as uid=1001 gid=1001 groups=65534(nobody),65534(nobody),1001
2024/10/18 19:14:58 INFO build user is uid=1000(build) gid=1000(build) groups=1000(build)
2024/10/18 19:14:58 INFO running sleep...
```

The running user in Bubblewrap is the very same user in the host considering the different user namespaces:

```shell
$ ls -l /proc/self/ns/user
lrwxrwxrwx. 1 massimiliano.giovagnoli massimiliano.giovagnoli 0 Oct 18 19:10 /proc/self/ns/user -> 'user:[4026531837]'
$ ls -l /proc/`pgrep -f "^sleep\ infinity$"`/ns/user
lrwxrwxrwx. 1 massimiliano.giovagnoli massimiliano.giovagnoli 0 Oct 18 19:20 /proc/855437/ns/user -> 'user:[4026533321]'
$ cat /proc/self/uid_map
         0          0 4294967295
$ cat /proc/`pgrep -f "^sleep\ infinity$`/uid_map
      1001       1001          1
$ ps -C sleep -o pid,cmd,user
    PID CMD                         USER
 855437 sleep infinity              massimiliano.giovagnoli # indeed
```

### Additional context

Moreover, if it's run with Docker runner, the behaviour is even different by default:

```shell
2024/10/18 19:37:40 INFO running as uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
2024/10/18 19:37:40 INFO build user is uid=1000(build) gid=1000(build) groups=1000(build)
2024/10/18 19:37:40 INFO running sleep infinity now...
```

```shell
$ ls -l /proc/`pgrep -f "^sleep\ infinity$"`/ns/user
lrwxrwxrwx. 1 root root 0 Oct 18 19:42 /proc/857591/ns/user -> 'user:[4026531837]'
$ ls -l /proc/self/ns/user
lrwxrwxrwx. 1 massimiliano.giovagnoli massimiliano.giovagnoli 0 Oct 18 19:45 /proc/self/ns/user -> 'user:[4026531837]'
```

Meaning that we can potentially have different results based on fileystem based on the runner.

Also, the CI runs Melange as `sudo melange` also with Bubblewrap, leading to always be uid 0 in the pipeline.

**Comment by maxgio92** [comment]
With #1572:

```
$ id -u
1001
$ melange build --runner bubblewrap test.yaml ...
...
2024/10/19 00:01:15 INFO running as uid=1000(build) gid=1000(build) groups=65534(nobody),65534(nobody),1000(build)
2024/10/19 00:01:15 INFO build user is uid=1000(build) gid=1000(build) groups=1000(build)
2024/10/19 00:01:15 INFO running sleep infinity now...
```
```shell
$ cat /proc/`pgrep -f "^sleep\ infinity$"`/{uid_map,gid_map}
      1000       1001          1
      1000       1001          1
```

**Comment by 89luca89** [comment]
From a little investigation, it turns out it's not the `cfg.RunAs` the problem, on the contrary it's when it's NOT specified
QEMU and Docker will fallback to run as root inside the sandbox
Bwrap defaults to running as "whatever user you are", hence the problem with missing users inside

The comments on the PR will fix this
