### ISSUE TITLE
Cannot use melange anymore without specify explict git repo url

### ISSUE THREAD

**Issue by shyim** [chainguard-dev/melange#1591]
Since commit https://github.com/chainguard-dev/melange/commit/eab3401f8019e134af6fe070e4d4bcff57993d30

I am no longer able to use Melange with default parameters.

Also, hard-coding the repo owners to your own namespace feels weird and is hacky

https://github.com/chainguard-dev/melange/blob/f63a1e357a3d868a06948a74624463a3354ceb95/pkg/cli/build.go#L297-L301

**Comment by luhring** [comment]
Yesterday's release should have fixed the issue with the build halting. Check that out and let me know if you're still seeing the issue.

We're going to solve the config repo URL issue a different way — opening a PR now for that...
