### ISSUE TITLE
releases are not completed for 0.14.{8,9}

### ISSUE THREAD

**Issue by chenrui333** [chainguard-dev/melange#1600]
👋 looks like the releasees are not completed for 0.14.8 and 0.14.9, raise issue for awareness. Thanks!

![Image](https://github.com/user-attachments/assets/56b458c2-4486-405b-9ec4-3ed9fee78d66)

**Comment by xnox** [comment]
these tags will not be marked as releases; as they were performed to test if automatic release process works or not; and trying to fix that.
