### ISSUE TITLE
Add way to generate VEX data for a package

### ISSUE THREAD

**Issue by luhring** [chainguard-dev/melange#205]
Each package (e.g. in Wolfi) should be able to have a corresponding VEX document.

We can generate that VEX document with Melange, by leveraging the `secfixes` data from the Melange config file. To do this, we just need to ensure that any data we'd use in the VEX document is available in the package's Melange config or the final apk itself.

Note: This means we probably need to extend the `secfixes` data structure to include additional VEX-related information, like impact and justfication.

**Proposal:** Add a new `vex` subcommand to `melange`. Something like this...

```console
$ melange vex ./config.yaml
{
  ...VEX JSON document...
}
```

**Comment by puerco** [comment]
I think the final form of this is now complete after these:
https://github.com/wolfi-dev/wolfictl/pull/7 https://github.com/wolfi-dev/wolfictl/pull/11 

@luhring should we close this one?

**Comment by dlorenc** [comment]
Closing, please reopen if there's still work!
