### ISSUE TITLE
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1' when tar the built package

### ISSUE THREAD

**Issue by tuananh** [chainguard-dev/melange#246]
when using `tar --list -f <my-package-r0>.apk`, i see a bunch of above warning.

probably not an issue but it would be nice to fix this?

**Comment by panekj** [comment]
I don't see anything to fix. apk uses custom headers for additional metadata and tar will always complain about those but tar isn't a right tool for `.apk` files.

**Comment by tuananh** [comment]
Thanks. Closing this then.
