### ISSUE TITLE
melange index after a build is beginning to take a long time as it processes the whole apk directory

### ISSUE THREAD

**Issue by rawlingsj** [chainguard-dev/melange#279]
I noticed that wolfi builds send a lot of time generating the APKINDEX after building each package.  I've only taken a quick peak at the code and saw that after the build we generate the index for a directory https://github.com/chainguard-dev/melange/blob/99e4df8b64ae4be46e8ff94311536dc5015867f0/pkg/build/build.go#L1392

I was wondering if it would be possible to add a single apk to the APKINDEX and avoid processing all packages?  Because in wolfi we fetch the entire contents of the bucket before a build it means over time this processing time will continue to grow.

I took a quick look and [adding a single package file](https://github.com/chainguard-dev/melange/blob/99e4df8b64ae4be46e8ff94311536dc5015867f0/pkg/index/index.go#L48) replaces the whole APKINDEX rather than updating it.  Assuming I've got that right I wonder if this is by design or if there's an improvement we can make here?

**Comment by rawlingsj** [comment]
i.e. there's lots of log entries like

```
2023-01-30T23:48:57.4601935Z 2023/01/30 23:48:57 melange: processing package /home/runner/work/os/os/packages/x86_64/tree-doc-2.0.4-r0.apk
2023-01-30T23:48:57.4609865Z 2023/01/30 23:48:57 melange: processing package /home/runner/work/os/os/packages/x86_64/tree-doc-2.1.0-r0.apk
2023-01-30T23:48:57.4632594Z 2023/01/30 23:48:57 melange: processing package /home/runner/work/os/os/packages/x86_64/tree-doc-2.1.0-r1.apk
2023-01-30T23:48:57.4640299Z 2023/01/30 23:48:57 melange: processing package /home/runner/work/os/os/packages/x86_64/tree-doc-2.1.0-r2.apk
```

**Comment by tuananh** [comment]
recent pr by @dlorenc https://github.com/chainguard-dev/melange/pull/236

**Comment by rawlingsj** [comment]
ah lol - love it! closing :)

**Comment by rawlingsj** [comment]
I guess it’s a slightly different approach to what I was thinking, rather than parallel if we could update the single package in the index but yeah this should help.  Will keep close and we can see how the parallel indexing helps.

**Comment by tuananh** [comment]
> I guess it’s a slightly different approach to what I was thinking, rather than parallel if we could update the single package in the index but yeah this should help. Will keep close and we can see how the parallel indexing helps.

i see. Helm did similar thing with `helm repo index` command where the command accepts a `--merge` flag.

https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/cmd/helm/repo_index.go#L93

**Comment by rawlingsj** [comment]
Yeah - maybe I'll reopen and see what folks think, we can always close again.
