### ISSUE TITLE
Bump apko dep, drop proot requirement

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/melange#315]
apko v0.7.0 dropped the need for `apk` to be installed, and instead manages apks with a pure Go implementation 🎉 

melange can pick up this updated dep and no longer need proot to protect its apk invocations

https://github.com/chainguard-dev/melange/pull/305 was my previous attempt, but there were some fs dep changes in 0.7.0 and it sounded like @deitch might have a better idea how to handle them.

Opening this so we can track this work and so we don't forget.

**Comment by kaniini** [comment]
Done!
