### ISSUE TITLE
failed to build package: unable to start pod: exit status 1

### ISSUE THREAD

**Issue by tuananh** [chainguard-dev/melange#381]
it seems a recent update to melange maybe related to this. i tested on a pkg that used to work before with this action 

https://github.com/chainguard-dev/actions/blob/main/setup-melange/action.yaml

```
Error: failed to build package: unable to start pod: exit status 1
2023/04/07 03:23:30 error during command execution: failed to build package: unable to start pod: exit status 1
```

also seeing this

```
bwrap: execvp /bin/sh: No such file or directory
2023/04/07 15:47:17 ERROR: failed to build package. the build environment has been preserved:
```

melange version
```
GitVersion:    v0.3.0-56-g25693bc
GitCommit:     25693bc25ee2a1b2869bc317408469e26951a243
GitTreeState:  clean
BuildDate:     '2023-04-06T19:45:13Z'
GoVersion:     go1.20.3
Compiler:      gc
Platform:      linux/amd64
```
any idea why?

**Comment by tuananh** [comment]
I just need to update to newer docker/setup-qemu-action version

**Comment by EzzOps** [comment]
hey @tuananh 
I got the same issue
![image](https://github.com/chainguard-dev/melange/assets/73319030/5e6c1e36-9c4e-4e94-a904-2e03c23e9972)
Is there a possible solution you found?
