### ISSUE TITLE
Including openjdk-11 and its subpackage openjdk-11-jre causes errors

### ISSUE THREAD

**Issue by patflynn** [chainguard-dev/melange#401]
If I use wolfi-base to `apk add`: `openjdk-11` and `openjdk-11-jre` everything seems to work hunky dory. 

When I include both of those packages in a melange file as deps to gradle-8 in wolfi I see:

```
Apr 22 16:15:19.965 [INFO] [arch:x86_64] installing openjdk-11-jre (11.0.19.5-r2)
Apr 22 16:15:26.771 [INFO] [arch:x86_64] installing gradle-8 (8.0.2-r2)
Apr 22 16:15:28.658 [INFO] [arch:x86_64] installing openjdk-11 (11.0.19.5-r2)
2023/04/22 16:15:34 ERROR: failed to build package. the build environment has been preserved:
2023/04/22 16:15:34 melange (gradle-8/x86_64):   workspace dir: /tmp/melange-workspace-1754311826
2023/04/22 16:15:34 melange (gradle-8/x86_64):   guest dir: /tmp/melange-guest-3403006330
Error: failed to build package: unable to build guest: unable to generate image: installing apk packages: unable to install files for pkg openjdk-11: error creating file usr/lib/jvm/openjdk/legal/java.base/ADDITIONAL_LICENSE_INFO: open /tmp/melange-guest-3403006330/usr/lib/jvm/openjdk/legal/java.base/ADDITIONAL_LICENSE_INFO: permission denied
2023/04/22 16:15:34 error during command execution: failed to build package: unable to build guest: unable to generate image: installing apk packages: unable to install files for pkg openjdk-11: error creating file usr/lib/jvm/openjdk/legal/java.base/ADDITIONAL_LICENSE_INFO: open /tmp/melange-guest-3403006330/usr/lib/jvm/openjdk/legal/java.base/ADDITIONAL_LICENSE_INFO: permission denied
make: *** [Makefile:82: packages/x86_64/gradle-8-8.1.1-r0.apk] Error 1
```

**Comment by deitch** [comment]
Oh, permission denied! That is a new one! Always up for some unexpected entertainment. 😄 

@patflynn can you put in here a minimal melange yaml that can reproduce it?

**Comment by patflynn** [comment]
[Here](https://gist.github.com/patflynn/82b32d3b8b8daf464b2b022441ac8cc8) you go!

**Comment by patflynn** [comment]
FYI the error changed after I installed melange from head.

**Comment by deitch** [comment]
Ah, good, I was able to reproduce it.

**Comment by patflynn** [comment]
I wasn't sure about this myself but `apk add` doesn't seem to complain about adding both.

**Comment by deitch** [comment]
That is a fair point. I wonder why that is. Worth digging a little more deeply into the APKINDEX.

How did you do an `apk add` manually?

**Comment by deitch** [comment]
They have the same origin, but conflicting files. I am hoping @kaniini can provide some insight.

**Comment by kaniini** [comment]
Packages with the same origin are allowed to override each other's files.

**Comment by patflynn** [comment]
@kaniini and I chatted about this this morning. Sounds like apko should allow overwriting in this case, but ideally I'd also fix-up the packages so that the jdk package is additive to its JRE subpackage rather than overlapping.

**Comment by deitch** [comment]
> Packages with the same origin are allowed to override each other's files.

Ah, ok. We can add that.

> jdk package is additive to its JRE subpackage rather than overlapping

I assume you mean in wolfi-dev/os?

**Comment by patflynn** [comment]
yep. seems less urgent once the overwriting is supported.

**Comment by deitch** [comment]
Actually this really is an apko issue.

**Comment by deitch** [comment]
Well, this is funny. Looking at apko logic, it actually _allows_ overwriting existing files, without regard to origin. It just says, "ok, I will overwrite this." This needs to be _constrained_ to only allow same origin, and then figure out why this particular case fails.
