### ISSUE TITLE
melange bump: doesn't work with `var-transforms`

### ISSUE THREAD

**Issue by rawlingsj** [chainguard-dev/melange#418]
I did have an initial attempt of getting melange bump to reuse pipeline mutation functions but that caused circular dependencies.  i.e. functions in the `build` package use function in `renovate` so `renovate` cannot use functions in `build`.

I bad attempt was this draft PR https://github.com/chainguard-dev/melange/pull/347 which refactored code under a single package but that is not good.  After chatting to @kaniini it sounds like some work planned here may help.

**Comment by Elizafox** [comment]
Once #586 is merged, this will be fixed.
