### ISSUE TITLE
Creation of custom pipelines?

### ISSUE THREAD

**Issue by blakepettersson** [chainguard-dev/melange#470]
It's not clear if it's possible to create custom pipelines. It would be good to be able to create and share such pipelines internally within an organization, or for iterating when developing/updating existing pipelines. 

If it's indeed possible to do so, then I guess it's a matter of adding some docs for it, and if not is there such a feature planned or being considered?

**Comment by kaniini** [comment]
It is possible to load additional pipelines with `--pipeline-dir`.  This directory will be scanned for any pipelines that are not built in.
