### ISSUE TITLE
Question about the baked in repos.

### ISSUE THREAD

**Issue by vaikas** [chainguard-dev/melange#638]
Would it be bad...

Currently when you run melange convert python, it adds the wolfi repos by default, here:
https://github.com/chainguard-dev/melange/blob/main/pkg/convert/python/python.go#L269

I think it would be nice to be able to pass a flag that those do not get added. Was thinking of just adding a flag --no-wolfi-repo (or something like that) and then a conditional right around the line above.

Context is to try to reduce manual mucking about after a file gets converted, and removing these for wolfi-dev/os repos is usually something that one always does manually. But maybe this assumption is wrong?

**Comment by kaniini** [comment]
I think any wolfi-specific behavior should be encoded in wolfictl, not melange.

**Comment by vaikas** [comment]
ok, but as a babystep:
 * Remove the hardcodes above (this also applies to things like gem, maybe others)
 * Add them as 'additional-repos' and 'additional-keyrings' in the "calling functions"
 * Add flag to not do ☝️ to keep the existing behaviour as is
 
 Then fix the other users to pass them in explicitly? WDYT?

**Comment by kaniini** [comment]
Yep, exactly, sounds good to me.

**Comment by vaikas** [comment]
This has been done.
