### ISSUE TITLE
Fail if a build results in an empty package

### ISSUE THREAD

**Issue by luhring** [chainguard-dev/melange#670]
Melange should detect and fail for the case where a built APK file was left with nothing but directories and an SBOM.

See motivation and context here: https://github.com/wolfi-dev/os/pull/5336#issuecomment-1712369082

**Comment by kaniini** [comment]
We need a way to allow this for some packages, like `build-base` and `wolfi-base`, which contain no actual data, but group dependencies together.

**Comment by Elizafox** [comment]
> We need a way to allow this for some packages, like `build-base` and `wolfi-base`, which contain no actual data, but group dependencies together.

Perhaps set something in the melange config stating the package is a metapackage? Something like:

```yaml
package:
  name: foobar
  empty: true
```

**Comment by Elizafox** [comment]
Also, this could easily be a linter.

**Comment by luhring** [comment]
> Perhaps set something in the melange config stating the package is a metapackage

I like the explicitness 👍

**Comment by Elizafox** [comment]
> > Perhaps set something in the melange config stating the package is a metapackage
> 
> I like the explicitness 👍

I found out there's already:

```yaml
package:
  options:
    no-provides: true
```

So I wrote the linter in #700 to respect it.

Incidentally, #700 will close this I believe.

**Comment by Elizafox** [comment]
Completed in #700. This lint can be disabled if needed.
