### ISSUE TITLE
Melange getting started docs

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/melange#70]
We really need some simple docs that explain:

 - what exactly melange is
 - why it's needed
 - how it works
 - how to get started

**Comment by amouat** [comment]
Unblocked, I'll take a look when I can. This might be a good issue for anyone @ltagliaferri @erikaheidi, but it probably needs a first pass by someone familiar with the project (the only docs so far are the code).

**Comment by erikaheidi** [comment]
I'd be happy to help with this one. Let me know if you'd prefer to give it the initial bootstrap.
