### ISSUE TITLE
Building for multiple archs simultaneously fails

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/melange#77]
Interestingly this works for me:

`melange build --arch x86_64 --empty-workspace melange.yaml`

and

`melange build --arch arm64 --empty-workspace melange.yaml`

But this fails:

`melange build --arch x86_64,arm64 --empty-workspace melange.yaml`

I'm trying to build the distroless/melange repo.

I think it's probably to do with needed to run in separate workspaces, I see in the output:

`2022/07/01 14:12:18 melange (melange/x86_64): fatal: destination path '.' already exists and is not an empty directory.`

**Comment by kaniini** [comment]
Looks like #77 is also resolved by #78.
