### ISSUE TITLE
failed to set xattrs when installing melange-built packages

### ISSUE THREAD

**Issue by joemiller** [chainguard-dev/melange#787]
We are running into issues with our custom melange-built packages. I am actually not sure when this started, it could have been an issue for a while.

Using melange v0.5.1 with the bubblewrap runner inside of a privileged docker container (somewhat necessary as we exec the builds on buildkite runners).

```console
/ # apk add shellcheck

(1/1) Installing shellcheck (0.9.0-r0)
ERROR: Failed to set xattrs on usr/bin/.apk.b2592835548f458f220d7183459e9d80ba205a157444f0c8: Operation not permitted
ERROR: Failed to set xattrs on var/lib/db/sbom/.apk.46e1e8fd5f33f5326cc20534e5457e3618b84872d84772c3: Operation not permitted
1 error; 31 MiB in 16 packages
```

strace:
```console
fsetxattr(8, "security.selinux", "system_u:object_r:var_lib_t:s0", 31, 0) = -1 EPERM (Operation not permitted)
```

Looking for ideas on how to solve this. Perhaps if there was a way to ignore xattrs altogether with `melange build`.

**Comment by joemiller** [comment]
I think these are being inherited from our CI build hosts where selinux is enabled and thus the files are inheriting the labels when melange builds the tarball. I can't easily turn selinux off on these hosts at the moment to test if that would prevent the inheritance, however. I'm thinking about specifically ignoring them in melange instead. 🤔

**Comment by joemiller** [comment]
It's worth noting that I only noticed these errors when running `apk add` to install melange-built packages. I have never noticed this when constructing images using `apko`. Perhaps apko does not try to restore these xattrs.

**Comment by kaniini** [comment]
Yes, apko does not try to restore these xattrs.
