### ISSUE TITLE
Add "melange index" to simplify generation of APK index

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-dev/melange#96]
In the "hello-melange-apko" repo, please see the following section: https://github.com/chainguard-dev/hello-melange-apko#generate-apk-repo-indexes

This is currently an extra step that users running through these steps manually need to run:

```
docker run --rm -it -v $(pwd):/w -w /w/packages -v $(pwd)/packages:/w/packages \
    --entrypoint sh \
    distroless.dev/melange -c \
        'for d in `find . -type d -mindepth 1`; do \
            ( \
                cd $d && \
                apk index -o APKINDEX.tar.gz *.apk && \
                melange sign-index --signing-key=../../melange.rsa APKINDEX.tar.gz\
            ) \
        done'
```

We should add a command to handle this, or perhaps a flag that automatically creates and signs the index after the APKs are successfully built.

**Comment by tuananh** [comment]
if you do it in CI, there's this action https://github.com/chainguard-dev/actions/blob/main/melange-index/action.yaml

**Comment by jdolitsky** [comment]
Thanks @tuananh. Yes, the action works well, I'm thinking more of UX for local development.

Perhaps another approach here is `melange build` can have a `--reindex` flag that does it for you. Or maybe it is the default.

**Comment by jdolitsky** [comment]
completed in #106 (and improved in #113)
